version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: weather_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather_logistics
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
